
import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'zh' | 'en';

type Translations = {
  [key: string]: string;
};

const translations: Record<Language, Translations> = {
  zh: {
    // Nav
    'brand.name': 'BeeDog',
    'nav.origin': '起源',
    'nav.board': '留言板',
    'nav.games': '游戏',
    'nav.tools': 'AI工具',
    'nav.shop': '商店',
    'nav.admin': '管理',
    'nav.switch': 'EN',
    'nav.login': '登录',
    'nav.missions': '任务',
    'nav.profile': '我的',

    // Hero
    'hero.tag': '火爆全网的狗狗表情包',
    'hero.title.1': '脸肿了',
    'hero.title.2': '但更强了',
    'hero.desc': '从抖音热榜到加密世界。我们是 $蜜蜂狗。生活虽然有时候会蛰你一下，但我们依然微笑面对。',
    'hero.buy': '立即购买',
    'hero.telegram': '加入电报群',

    // Narrative
    'narrative.title': '不仅仅是 Meme',
    'narrative.subtitle': '这是我们的精神图腾',
    'narrative.card1.title': '抖音/TikTok 爆火起源',
    'narrative.card1.desc': '一切始于一只好奇心太重的修勾。它只是想尝尝蜂蜜的味道，结果变成了全网最“圆润”的狗子。#蜜蜂狗标签在抖音和 TikTok 上获得了十亿次播放，它那种“滑稽但又无辜”的眼神，击中了无数人的心。',
    'narrative.card2.title': '微信社交货币',
    'narrative.card2.desc': '在微信上，蜜蜂狗已经成为了年轻人的“赛博替身”。当你不想上班时，当你被生活“蛰”了一下时，一张蜜蜂狗表情包胜过千言万语。它是我们表达情绪的一种方式。',

    // Community
    'comm.title': '蜜蜂狗社区',
    'comm.subtitle': '去中心化，社区驱动，永不 Rug。',
    'comm.cto.title': '100% 社区接管 (CTO)',
    'comm.cto.desc': '没有 VC，没有项目方，没有老鼠仓。就像蜜蜂筑巢一样，每一个 $蜜蜂狗 的持有者都在为社区添砖加瓦。',
    'comm.meme.title': '无限 Meme 潜力',
    'comm.meme.desc': '素材库每天更新，二创内容层出不穷。每一个表情包都是传播的种子。',
    'comm.meme.quote': '“一张好图胜过千言万语，蜜蜂狗就是最好的语言。”',
    'comm.meme.btn': '去制作表情包',
    'comm.shield.title': '抗击打能力强',
    'comm.shield.desc': '经历过市场的毒打，脸虽然肿了，但钻石手从未松开。',
    'comm.global.title': '全球共识',
    'comm.global.desc': '不分国界，每个人都能看懂这只肿脸狗的委屈。',

    // Token
    'token.title': '代币经济',
    'token.desc': '简单透明的机制',
    'token.supply': '总供应量',
    'token.contract': '合约地址',

    // Roadmap
    'roadmap.title': '未来计划',
    'roadmap.p1.phase': '起步阶段',
    'roadmap.p1.title': '网络爆火',
    'roadmap.p1.i1': '抖音/TikTok 播放量破亿',
    'roadmap.p1.i2': '微信表情包下载量激增',
    'roadmap.p1.i3': '社区 CTO (接管) 项目',
    'roadmap.p1.i4': '去中心化公平发射',
    'roadmap.p2.phase': '成长阶段',
    'roadmap.p2.title': '文化输出',
    'roadmap.p2.i1': '蜜蜂狗 周边实体玩偶',
    'roadmap.p2.i2': 'KOL 病毒式传播',
    'roadmap.p2.i3': '持有者突破 10,000+',
    'roadmap.p2.i4': 'Meme 创意大赛',
    'roadmap.p3.phase': '最终阶段',
    'roadmap.p3.title': '爆发增长',
    'roadmap.p3.i1': '币安阿尔法上市',
    'roadmap.p3.i2': '蜜蜂狗慈善基金 (救助流浪狗)',
    'roadmap.p3.i3': '币安合约上市',
    'roadmap.p3.i4': '成为 Meme 界的顶流 IP',

    // Footer
    'footer.desc': '蜜蜂狗社区',
    'footer.risk': '加密货币投资具有高风险，请理性投资。',
    'footer.copy': '© 2024 BeeDog. All rights reserved.',

    // Auth
    'auth.welcome': '欢迎回来',
    'auth.join': '加入我们',
    'auth.login_desc': '登录以保存游戏进度',
    'auth.register_desc': '创建新账号',
    'auth.twitter': 'Twitter 登录',
    'auth.or': '或',
    'auth.email_placeholder': '邮箱地址',
    'auth.pwd_placeholder': '密码',
    'auth.forgot_pwd': '忘记密码?',
    'auth.login_btn': '登录',
    'auth.no_account': '没有账号?',
    'auth.go_register': '去注册',
    'auth.has_account': '已有账号?',
    'auth.go_login': '去登录',
    'auth.register_btn': '注册',
    'auth.forgot_title': '重置密码',
    'auth.forgot_desc': '输入邮箱接收重置链接',
    'auth.send_reset': '发送链接',
    'auth.back_login': '返回登录',

    // Profile
    'profile.title': '个人中心',
    'profile.manage': '管理你的账户',
    'profile.no_email': '未绑定邮箱',
    'profile.honey_balance': '蜂蜜余额',
    'profile.linked_acc': '关联账户',
    'profile.bind_x_done': '已绑定 Twitter',
    'profile.bind_x': '绑定 Twitter',
    'profile.bind_email_done': '已绑定邮箱',
    'profile.bind_email': '绑定邮箱',
    'profile.logout': '退出登录',

    // Tools
    'tools.back': '返回',
    'tools.title': 'AI 工具箱',
    'tools.subtitle': '赋能社区创作',
    'tools.use_now': '立即使用',
    'tools.hot': '热门',
    'tools.new': '新品',
    'tools.daily': '每日',

    // PFP
    'tools.pfp.title': '头像生成器',
    'tools.pfp.desc': '打造你的专属蜜蜂狗头像',
    'pfp.mode.role': '角色扮演',
    'pfp.mode.parts': '部件组合',
    'pfp.theme': '主题',
    'pfp.role': '角色',
    'pfp.details': '细节',
    'pfp.head': '头部',
    'pfp.eyes': '眼睛',
    'pfp.outfit': '服装',
    'pfp.item': '道具',
    'pfp.ref_img': '参考图 (可选)',
    'pfp.bg_style': '背景风格',

    // Meme
    'tools.meme.title': '表情包工坊',
    'tools.meme.desc': '一键生成全套表情包',
    'meme.style': '风格',
    'meme.define': '定义标签',
    'meme.limit': '最多9个标签',
    'meme.add_input': '输入标签...',
    'meme.hint': '回车添加',
    'meme.result_title': '生成结果',
    'meme.zip': '打包下载',

    // Selfie
    'tools.selfie.title': '合影生成器',
    'tools.selfie.desc': '和你的朋友们一起合影',
    'selfie.upload_label': '上传角色图',
    'selfie.add_slot': '添加位置',
    'selfie.style': '风格',
    'selfie.scene': '场景',
    'selfie.btn': '生成合影',

    // Fortune
    'tools.fortune.title': 'AI 算命',
    'tools.fortune.desc': '测测今天的运势',
    'divine.name': '姓名',
    'divine.date': '出生日期',
    'divine.solar': '阳历',
    'divine.lunar': '阴历',
    'divine.time': '出生时辰',
    'divine.location': '出生地点',
    'divine.btn': '开始测算',
    'divine.today_done': '今日已测',
    'divine.history': '历史记录',
    'divine.result.level': '运势等级',
    'divine.result.color': '幸运色',
    'divine.result.num': '幸运数',
    'divine.result.dir': '吉位',
    'divine.result.analysis': '详细解析',

    // AI General
    'ai.click_upload': '点击上传',
    'ai.upload_base': '上传底图',
    'ai.clear': '清除',
    'ai.generating': '生成中...',
    'ai.finished': '完成',
    'ai.waiting': '等待中',
    'ai.honey_left': '剩余蜂蜜',
    'ai.start': '开始生成',
    'ai.download': '下载',
    'ai.reset': '重置',
    'ai.login_hint': '请先登录使用',

    // Games
    'games.lobby': '游戏大厅',
    'games.logged_in': '已登录',
    'games.login_save': '登录存档',
    'games.select': '选择游戏',
    'games.earn_honey': '赚取蜂蜜',
    'games.play_now': '开始游戏',
    'games.how_to_play': '玩法说明',
    'games.leaderboard': '排行榜',
    'games.reviews': '评价',
    'games.my_best': '我的最佳',
    'games.all_games': '所有游戏',
    'games.select_hint': '点击选择游戏',

    // Game Titles
    'game.honey_jump.name': '蜂蜜跳一跳',
    'game.honey_jump.desc': '蓄力跳跃，探索更高处。',
    'game.honey_farm.name': '蜜蜂农场',
    'game.honey_farm.desc': '种植作物，躺着赚蜂蜜。',
    'game.honey_fishing.name': '垂钓大师',
    'game.honey_fishing.desc': '钓鱼佬永不空军！',
    'game.bee_knight.name': '蜜蜂骑士',
    'game.bee_knight.desc': '极速送餐，躲避障碍。',
    'game.flappy_bee.name': '笨鸟先飞',
    'game.flappy_bee.desc': '经典玩法，挑战极限。',
    'game.honey_miner.name': '黄金矿工',
    'game.honey_miner.desc': '抓取比特币和以太坊！',
    'game.bee_defense.name': '保卫狗头',
    'game.bee_defense.desc': '拍死蜜蜂，保护狗狗。',
    'game.bee_racing.name': '极速赛车',
    'game.bee_racing.desc': '左右变道，极速狂飙。',
    'game.bee_snake.name': '贪吃蛇',
    'game.bee_snake.desc': '吃掉蜂蜜变长。',
    'game.bee_volley.name': '沙滩排球',
    'game.bee_volley.desc': '别让球落地！',
    'game.bee_run.name': '重力跑酷',
    'game.bee_run.desc': '反转重力，穿越隧道。',
    'game.honey_stack.name': '堆蛋糕',
    'game.honey_stack.desc': '完美重叠，堆得更高。',
    'game.fud_buster.name': '切水果',
    'game.fud_buster.desc': '切碎 FUD，保护绿线。',
    'game.bee_evolution.name': '合成大蜜蜂',
    'game.bee_evolution.desc': '2048 玩法，合成进化。',
    'game.bee_tile_match.name': '羊了个羊',
    'game.bee_tile_match.desc': '消除三个相同图案。',
    'game.honey_climber.name': '爬树高手',
    'game.honey_climber.desc': '左右闪避，快速攀爬。',
    'game.honey_swing.name': '蜘蛛侠',
    'game.honey_swing.desc': '像蜘蛛侠一样飞荡。',
    'game.honey_slots.name': '老虎机',
    'game.honey_slots.desc': '试试手气，赢取大奖。',
    'game.honey_burger.name': '做汉堡',
    'game.honey_burger.desc': '记忆配方，制作汉堡。',
    'game.honey_scratch.name': '刮刮乐',
    'game.honey_scratch.desc': '刮开图层，集齐三个图案中奖。',
    'game.moon_doom.name': '传奇交易员',
    'game.moon_doom.desc': '真实行情模拟，做多做空赚收益。',
    'game.bee_swarm.name': '蜜蜂突围',
    'game.bee_swarm.desc': '聚集蜂群，冲破障碍。',
    'game.honey_dozer.name': '推金币',
    'game.honey_dozer.desc': '经典推币机玩法。',

    // Shop
    'shop.title': '蜂蜜商店',
    'shop.subtitle': '兑换周边与虚拟物品',
    'shop.tab.store': '商品列表',
    'shop.tab.orders': '我的订单',
    'shop.empty': '暂无商品',
    'shop.sold_out': '已售罄',
    'shop.limit_reached': '限购',
    'shop.stock': '库存',
    'shop.limit': '限购 {n}',
    'shop.redeem': '兑换',
    'shop.empty_orders': '暂无订单',
    'shop.order.paid': '实付',
    'shop.order.status.completed': '已完成',
    'shop.order.status.rejected': '已拒绝',
    'shop.order.status.pending': '处理中',
    'shop.confirm.title': '确认兑换',
    'shop.confirm.desc': '请填写收货信息',
    'shop.confirm.processing': '处理中...',
    'shop.confirm.btn': '确认支付',

    // Mission
    'mission.title': '任务中心',
    'mission.tab.earn': '赚蜂蜜',
    'mission.tab.leaderboard': '排行榜',
    'mission.tab.guide': '指南',
    'mission.desc': '完成任务获取蜂蜜，用于游戏和兑换。',
    'mission.checkin.title': '每日签到',
    'mission.checkin.desc': '每天来领低保',
    'mission.checkin.done': '已签到',
    'mission.checkin.btn': '签到',
    'mission.game.title': '每日首玩',
    'mission.game.desc': '玩任意游戏一局',
    'mission.game.btn': '去玩游戏',
    'mission.leaderboard.title': '财富榜',
    'mission.leaderboard.desc': '谁是蜂蜜大户？',
    'mission.my_rank': '我的排名',
    'mission.my_assets': '我的资产',
    'mission.guide.what': '什么是蜂蜜？',
    'mission.guide.what_desc': '蜂蜜是 BeeDog 社区的积分，通过游戏和任务获得。',
    'mission.guide.use': '用途',
    'mission.guide.use_game': '玩游戏 (如抓娃娃)',
    'mission.guide.use_ai': '使用 AI 工具',
    'mission.guide.use_future': '兑换周边',
    'mission.guide.disclaimer': '免责声明',
    'mission.guide.disclaimer_desc': '蜂蜜仅为娱乐积分，无货币价值。',

    // Board
    'board.title': '社区留言板',
    'board.desc': '留下你的足迹，全网可见',
    'board.placeholder': '说点什么...',
    'board.login_to_post': '登录后留言',
    'board.empty': '暂无留言',
    'board.be_first': '成为第一个留言的人！',
    'board.warn': '请文明发言',
  },
  en: {
    // Nav
    'brand.name': 'BeeDog',
    'nav.origin': 'Origin',
    'nav.board': 'Board',
    'nav.games': 'Games',
    'nav.tools': 'AI Tools',
    'nav.shop': 'Shop',
    'nav.admin': 'Admin',
    'nav.switch': '中',
    'nav.login': 'Login',
    'nav.missions': 'Missions',
    'nav.profile': 'Profile',

    // Hero
    'hero.tag': 'Viral Dog Meme',
    'hero.title.1': 'Face Swollen',
    'hero.title.2': 'But Stronger',
    'hero.desc': 'From trending on TikTok to the crypto world. We are $BeeDog. Life stings sometimes, but we smile through it.',
    'hero.buy': 'Buy $BEEDOG',
    'hero.telegram': 'Join Telegram',

    // Narrative
    'narrative.title': 'Not Just A Meme',
    'narrative.subtitle': 'Our Spiritual Totem',
    'narrative.card1.title': 'Viral Origin',
    'narrative.card1.desc': 'It started with a curious puppy tasting honey. #BeeDog has billions of views. Funny yet innocent.',
    'narrative.card2.title': 'Social Currency',
    'narrative.card2.desc': 'The cyber avatar for youth. When life stings, a BeeDog meme speaks a thousand words.',

    // Community
    'comm.title': 'BeeDog Community',
    'comm.subtitle': 'Decentralized, Community Driven, Never Rug.',
    'comm.cto.title': '100% CTO',
    'comm.cto.desc': 'No VC, No Team, No Rat Trading. Holders build the hive.',
    'comm.meme.title': 'Infinite Meme Potential',
    'comm.meme.desc': 'Daily updates. Every meme is a seed.',
    'comm.meme.quote': '“A good picture is worth a thousand words, BeeDog is the best language.”',
    'comm.meme.btn': 'Generate Now',
    'comm.shield.title': 'Resilient',
    'comm.shield.desc': 'Face swollen from beatings, but diamond hands hold tight.',
    'comm.global.title': 'Global Consensus',
    'comm.global.desc': 'No borders, everyone understands the swollen dog.',

    // Token
    'token.title': 'Tokenomics',
    'token.desc': 'Simple and Transparent',
    'token.supply': 'Total Supply',
    'token.contract': 'Contract',

    // Roadmap
    'roadmap.title': 'The Plan',
    'roadmap.p1.phase': 'Phase 1',
    'roadmap.p1.title': 'Viral Start',
    'roadmap.p1.i1': '100M+ Views',
    'roadmap.p1.i2': 'Sticker Downloads',
    'roadmap.p1.i3': 'Community CTO',
    'roadmap.p1.i4': 'Fair Launch',
    'roadmap.p2.phase': 'Phase 2',
    'roadmap.p2.title': 'Culture Export',
    'roadmap.p2.i1': 'BeeDog Plushies',
    'roadmap.p2.i2': 'KOL Viral',
    'roadmap.p2.i3': '10k+ Holders',
    'roadmap.p2.i4': 'Meme Contest',
    'roadmap.p3.phase': 'Phase 3',
    'roadmap.p3.title': 'Explosion',
    'roadmap.p3.i1': 'Tier 1 Listing',
    'roadmap.p3.i2': 'Charity Fund',
    'roadmap.p3.i3': 'Futures Listing',
    'roadmap.p3.i4': 'Top Meme IP',

    // Footer
    'footer.desc': 'BeeDog Community',
    'footer.risk': 'Crypto investment is high risk. DYOR.',
    'footer.copy': '© 2024 BeeDog. All rights reserved.',

    // Auth
    'auth.welcome': 'Welcome Back',
    'auth.join': 'Join Us',
    'auth.login_desc': 'Login to save progress',
    'auth.register_desc': 'Create Account',
    'auth.twitter': 'Login with Twitter',
    'auth.or': 'OR',
    'auth.email_placeholder': 'Email Address',
    'auth.pwd_placeholder': 'Password',
    'auth.forgot_pwd': 'Forgot Password?',
    'auth.login_btn': 'Login',
    'auth.no_account': 'No account?',
    'auth.go_register': 'Register',
    'auth.has_account': 'Have account?',
    'auth.go_login': 'Login',
    'auth.register_btn': 'Register',
    'auth.forgot_title': 'Reset Password',
    'auth.forgot_desc': 'Enter email to reset',
    'auth.send_reset': 'Send Link',
    'auth.back_login': 'Back to Login',

    // Profile
    'profile.title': 'Profile',
    'profile.manage': 'Manage Account',
    'profile.no_email': 'No Email',
    'profile.honey_balance': 'Honey Balance',
    'profile.linked_acc': 'Linked Accounts',
    'profile.bind_x_done': 'Twitter Linked',
    'profile.bind_x': 'Link Twitter',
    'profile.bind_email_done': 'Email Linked',
    'profile.bind_email': 'Link Email',
    'profile.logout': 'Logout',

    // Tools
    'tools.back': 'Back',
    'tools.title': 'AI Toolbox',
    'tools.subtitle': 'Empowering Creation',
    'tools.use_now': 'Use Now',
    'tools.hot': 'HOT',
    'tools.new': 'NEW',
    'tools.daily': 'DAILY',

    // PFP
    'tools.pfp.title': 'PFP Maker',
    'tools.pfp.desc': 'Create your unique PFP',
    'pfp.mode.role': 'Roleplay',
    'pfp.mode.parts': 'Parts',
    'pfp.theme': 'Theme',
    'pfp.role': 'Role',
    'pfp.details': 'Details',
    'pfp.head': 'Head',
    'pfp.eyes': 'Eyes',
    'pfp.outfit': 'Outfit',
    'pfp.item': 'Item',
    'pfp.ref_img': 'Ref Image (Optional)',
    'pfp.bg_style': 'Background',

    // Meme
    'tools.meme.title': 'Meme Lab',
    'tools.meme.desc': 'Generate Sticker Pack',
    'meme.style': 'Style',
    'meme.define': 'Labels',
    'meme.limit': 'Max 9 labels',
    'meme.add_input': 'Add label...',
    'meme.hint': 'Enter to add',
    'meme.result_title': 'Results',
    'meme.zip': 'Download ZIP',

    // Selfie
    'tools.selfie.title': 'Group Selfie',
    'tools.selfie.desc': 'Take a selfie with friends',
    'selfie.upload_label': 'Upload Characters',
    'selfie.add_slot': 'Add Slot',
    'selfie.style': 'Style',
    'selfie.scene': 'Scene',
    'selfie.btn': 'Generate Selfie',

    // Fortune
    'tools.fortune.title': 'AI Fortune',
    'tools.fortune.desc': 'Daily Fortune',
    'divine.name': 'Name',
    'divine.date': 'Date of Birth',
    'divine.solar': 'Solar',
    'divine.lunar': 'Lunar',
    'divine.time': 'Time',
    'divine.location': 'Location',
    'divine.btn': 'Divinate',
    'divine.today_done': 'Done Today',
    'divine.history': 'History',
    'divine.result.level': 'Level',
    'divine.result.color': 'Lucky Color',
    'divine.result.num': 'Lucky Number',
    'divine.result.dir': 'Direction',
    'divine.result.analysis': 'Analysis',

    // AI General
    'ai.click_upload': 'Click Upload',
    'ai.upload_base': 'Base Image',
    'ai.clear': 'Clear',
    'ai.generating': 'Generating...',
    'ai.finished': 'Finished',
    'ai.waiting': 'Waiting',
    'ai.honey_left': 'Honey Left',
    'ai.start': 'Start',
    'ai.download': 'Download',
    'ai.reset': 'Reset',
    'ai.login_hint': 'Please login',

    // Games
    'games.lobby': 'Game Lobby',
    'games.logged_in': 'Logged In',
    'games.login_save': 'Login to Save',
    'games.select': 'Select Game',
    'games.earn_honey': 'Earn Honey',
    'games.play_now': 'Play Now',
    'games.how_to_play': 'How to Play',
    'games.leaderboard': 'Leaderboard',
    'games.reviews': 'Reviews',
    'games.my_best': 'My Best',
    'games.all_games': 'All Games',
    'games.select_hint': 'Click to select',

    // Game Titles
    'game.honey_jump.name': 'Honey Jump',
    'game.honey_jump.desc': 'Charge and jump to the sky.',
    'game.honey_farm.name': 'Honey Farm',
    'game.honey_farm.desc': 'Plant and earn honey idle.',
    'game.honey_fishing.name': 'Fishing Master',
    'game.honey_fishing.desc': 'Catch rare fish!',
    'game.bee_knight.name': 'Bee Knight',
    'game.bee_knight.desc': 'Deliver food, dodge cars.',
    'game.flappy_bee.name': 'Flappy Bee',
    'game.flappy_bee.desc': 'Classic flying challenge.',
    'game.honey_miner.name': 'Honey Miner',
    'game.honey_miner.desc': 'Grab BTC and ETH!',
    'game.bee_defense.name': 'Bee Defense',
    'game.bee_defense.desc': 'Smack bees, save dog.',
    'game.bee_racing.name': 'Bee Racing',
    'game.bee_racing.desc': 'Dodge traffic at high speed.',
    'game.bee_snake.name': 'Bee Snake',
    'game.bee_snake.desc': 'Eat honey to grow.',
    'game.bee_volley.name': 'Bee Volley',
    'game.bee_volley.desc': 'Don\'t let the ball drop!',
    'game.bee_run.name': 'Gravity Run',
    'game.bee_run.desc': 'Flip gravity, run fast.',
    'game.honey_stack.name': 'Honey Stack',
    'game.honey_stack.desc': 'Stack blocks perfectly.',
    'game.fud_buster.name': 'FUD Buster',
    'game.fud_buster.desc': 'Slice FUD, keep green.',
    'game.bee_evolution.name': 'Bee Evolution',
    'game.bee_evolution.desc': 'Merge balls to evolve.',
    'game.bee_tile_match.name': 'Bee Match',
    'game.bee_tile_match.desc': 'Match 3 tiles.',
    'game.honey_climber.name': 'Honey Climber',
    'game.honey_climber.desc': 'Climb fast, dodge branches.',
    'game.honey_swing.name': 'Honey Swing',
    'game.honey_swing.desc': 'Swing like Spiderman.',
    'game.honey_slots.name': 'Honey Slots',
    'game.honey_slots.desc': 'Spin to win big.',
    'game.honey_burger.name': 'Honey Burger',
    'game.honey_burger.desc': 'Memorize and build burgers.',
    'game.honey_scratch.name': 'Scratch Card',
    'game.honey_scratch.desc': 'Scratch for surprise.',
    'game.moon_doom.name': 'Legendary Trader',
    'game.moon_doom.desc': 'Simulate crypto trading.',
    'game.bee_swarm.name': 'Bee Swarm',
    'game.bee_swarm.desc': 'Gather swarm, break through.',
    'game.honey_dozer.name': 'Honey Dozer',
    'game.honey_dozer.desc': 'Coin pusher arcade.',

    // Shop
    'shop.title': 'Honey Shop',
    'shop.subtitle': 'Redeem Merch & Items',
    'shop.tab.store': 'Store',
    'shop.tab.orders': 'Orders',
    'shop.empty': 'No products',
    'shop.sold_out': 'Sold Out',
    'shop.limit_reached': 'Limit',
    'shop.stock': 'Stock',
    'shop.limit': 'Limit {n}',
    'shop.redeem': 'Redeem',
    'shop.empty_orders': 'No orders',
    'shop.order.paid': 'Paid',
    'shop.order.status.completed': 'Completed',
    'shop.order.status.rejected': 'Rejected',
    'shop.order.status.pending': 'Pending',
    'shop.confirm.title': 'Confirm',
    'shop.confirm.desc': 'Enter Details',
    'shop.confirm.processing': 'Processing...',
    'shop.confirm.btn': 'Pay',

    // Mission
    'mission.title': 'Mission Center',
    'mission.tab.earn': 'Earn',
    'mission.tab.leaderboard': 'Leaderboard',
    'mission.tab.guide': 'Guide',
    'mission.desc': 'Complete missions to earn Honey.',
    'mission.checkin.title': 'Daily Check-in',
    'mission.checkin.desc': 'Free honey daily',
    'mission.checkin.done': 'Checked In',
    'mission.checkin.btn': 'Check In',
    'mission.game.title': 'Daily Play',
    'mission.game.desc': 'Play any game once',
    'mission.game.btn': 'Play Game',
    'mission.leaderboard.title': 'Rich List',
    'mission.leaderboard.desc': 'Who has most honey?',
    'mission.my_rank': 'My Rank',
    'mission.my_assets': 'My Assets',
    'mission.guide.what': 'What is Honey?',
    'mission.guide.what_desc': 'Honey is community points earned by playing.',
    'mission.guide.use': 'Uses',
    'mission.guide.use_game': 'Play Games',
    'mission.guide.use_ai': 'Use AI Tools',
    'mission.guide.use_future': 'Redeem Merch',
    'mission.guide.disclaimer': 'Disclaimer',
    'mission.guide.disclaimer_desc': 'Honey is for entertainment only.',

    // Board
    'board.title': 'Community Board',
    'board.desc': 'Leave your mark',
    'board.placeholder': 'Say something...',
    'board.login_to_post': 'Login to post',
    'board.empty': 'No messages',
    'board.be_first': 'Be the first!',
    'board.warn': 'Be polite',
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: any) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('zh'); // Default to Chinese

  const t = (key: string, params?: any): string => {
    let text = translations[language][key] || translations['en'][key] || key;
    if (params) {
        Object.keys(params).forEach(k => {
            text = text.replace(`{${k}}`, params[k]);
        });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
