import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'zh' | 'en';

type Translations = {
  [key: string]: string;
};

const translations: Record<Language, Translations> = {
  zh: {
    // Nav
    'brand.name': 'BeeDog',
    'nav.origin': '起源',
    'nav.board': '留言板',
    'nav.games': '游戏',
    'nav.tools': 'AI工具',
    'nav.shop': '商店',
    'nav.admin': '管理',
    'nav.switch': 'EN',
    'nav.login': '登录',
    'nav.missions': '任务',
    'nav.profile': '我的',

    // Hero
    'hero.tag': '火爆全网的狗狗表情包',
    'hero.title.1': '脸肿了',
    'hero.title.2': '但更强了',
    'hero.desc': '从抖音热榜到加密世界。我们是 $BeeDog。生活虽然有时候会蛰你一下，但我们依然微笑面对，毕竟肿起来的脸里装的全是财富与梦想。',
    'hero.buy': '立即购买',
    'hero.telegram': '加入电报群',

    // Narrative
    'narrative.title': '核心叙事：委屈中的坚韧',
    'narrative.subtitle': '它是表情包，更是我们的精神图腾',
    'narrative.card1.title': '被市场“蛰”过的每一个人',
    'narrative.card1.desc': '蜜蜂狗的起源是一张意外爆火的照片：一只迷你杜宾犬因为贪吃蜂蜜，脸部被蜜蜂蛰得高高肿起。这种“既委屈又好笑”的视觉冲突，完美契合了加密市场散户的心境——我们都被狗庄、被波动的行情“蛰”过，脸虽然肿了，但眼神中依然透着对蜂蜜（利润）的渴望。这是属于所有底层投资者的自嘲与坚持。',
    'narrative.card2.title': '从热梗到社交货币',
    'narrative.card2.desc': '在微信、抖音和 TikTok 上，#蜜蜂狗 的标签拥有数十亿的播放量。它已经脱离了宠物的范畴，成为一种表达“生活很苦，但我很萌”的社交语言。当你不想上班、想借钱、或者刚被行情套牢时，一张蜜蜂狗的表情包就是最好的共情。它是全世界通用的语言，因为它触及了人性中最真实的一面：在逆境中保持幽默。',

    // Community
    'comm.title': '社区发展历程',
    'comm.subtitle': '从被遗弃到自我拯救的史诗。',
    'comm.cto.title': '100% 社区接管 (CTO) 的传奇',
    'comm.cto.desc': '蜜蜂狗最初由一名匿名开发者发布，但在项目刚起步时，开发者便选择了放弃。社区成员没有眼睁睁看着它归零，而是发起了史无前例的“自救行动”。没有 VC 操盘，没有老鼠仓。我们通过去中心化的协作，重组了技术团队，建立了治理小组。就像蜜蜂筑巢一样，每一块砖瓦都是由真实的持有者亲手垒起。',
    'comm.meme.title': '文化共建实验室',
    'comm.meme.desc': '我们的社区成员是天才的二创家。从火影蜜蜂狗到赛博蜜蜂狗，每天都有数百张新表情包产生。这不仅仅是代币，这是一个活着的 IP。',
    'comm.meme.quote': '“项目方会跑路，但表情包永存。只要还有人在发蜜蜂狗，共识就在增长。”',
    'comm.meme.btn': '去制作表情包',
    'comm.shield.title': '钻石手的试炼',
    'comm.shield.desc': '经历过无数次深V反转，社区在波动中筛选出了最纯粹的信仰者。脸肿了没关系，消肿之后就是月球。',
    'comm.global.title': '全球化扩张',
    'comm.global.desc': '从中文社区爆发，迅速蔓延至东南亚、欧洲和北美。蜜蜂狗正在成为全球最“粘”的社区代币。',

    // Token
    'token.title': '代币经济',
    'token.desc': '简单透明，完全属于社区。没有复杂的锁仓，没有隐藏的抛压。',
    'token.supply': '总供应量',
    'token.contract': '合约地址',

    // Roadmap
    'roadmap.title': '消肿计划 (Roadmap)',
    'roadmap.p1.phase': '第一阶段',
    'roadmap.p1.title': '播种蜂蜜',
    'roadmap.p1.i1': '社区 1.0 Infrastructure 搭建',
    'roadmap.p1.i2': '表情包库全球同步更新',
    'roadmap.p1.i3': '完成 50+ 顶级 KOL 深度合作',
    'roadmap.p1.i4': '上线基础款 AI 头像工具',
    'roadmap.p2.phase': '第二阶段',
    'roadmap.p2.title': '全网肿脸',
    'roadmap.p2.i1': '蜜蜂狗 联名周边 (实体盲盒)',
    'roadmap.p2.i2': '举办全球 Meme 视频创意大赛',
    'roadmap.p2.i3': '持有者突破 50,000+',
    'roadmap.p2.i4': '集成更多高收益 Web3 游戏',
    'roadmap.p3.phase': '第三阶段',
    'roadmap.p3.title': '飞向月球',
    'roadmap.p3.i1': '顶级中心化交易所 (CEX) 上币',
    'roadmap.p3.i2': '启动“蜜蜂狗关爱计划”慈善基金',
    'roadmap.p3.i3': '上线 BeeDog 元宇宙社交空间',
    'roadmap.p3.i4': '成为全球排名前十的 Meme 代币',

    // Footer
    'footer.desc': '蜜蜂狗：一个为了吃蜂蜜不怕被蛰的社区。',
    'footer.risk': '投资有风险，购买 $BeeDog 前请确保你拥有一颗强大的大心脏。',
    'footer.copy': '© 2024 BeeDog Community. 由钻石手共同驱动。',

    // Auth
    'auth.welcome': '欢迎回来',
    'auth.join': '加入我们',
    'auth.login_desc': '登录以保存游戏进度',
    'auth.register_desc': '创建新账号',
    'auth.twitter': 'Twitter 登录',
    'auth.or': '或',
    'auth.email_placeholder': '邮箱地址',
    'auth.pwd_placeholder': '密码',
    'auth.forgot_pwd': '忘记密码?',
    'auth.login_btn': '登录',
    'auth.no_account': '没有账号?',
    'auth.go_register': '去注册',
    'auth.has_account': '已有账号?',
    'auth.go_login': '去登录',
    'auth.register_btn': '注册',
    'auth.forgot_title': '重置密码',
    'auth.forgot_desc': '输入邮箱接收重置链接',
    'auth.send_reset': '发送链接',
    'auth.back_login': '返回登录',

    // Profile
    'profile.title': '个人中心',
    'profile.manage': '管理你的账户',
    'profile.no_email': '未绑定邮箱',
    'profile.honey_balance': '蜂蜜余额',
    'profile.linked_acc': '关联账户',
    'profile.bind_x_done': '已绑定 Twitter',
    'profile.bind_x': '绑定 Twitter',
    'profile.bind_email_done': '已绑定邮箱',
    'profile.bind_email': '绑定邮箱',
    'profile.logout': '退出登录',

    // Tools
    'tools.back': '返回',
    'tools.title': 'AI 工具箱',
    'tools.subtitle': '赋能社区创作',
    'tools.use_now': '立即使用',
    'tools.hot': '热门',
    'tools.new': '新品',
    'tools.daily': '每日',

    // PFP
    'tools.pfp.title': '头像生成器',
    'tools.pfp.desc': '打造你的专属蜜蜂狗头像',
    'pfp.mode.role': '角色扮演',
    'pfp.mode.parts': '部件组合',
    'pfp.theme': '主题',
    'pfp.role': '角色',
    'pfp.details': '细节',
    'pfp.head': '头部',
    'pfp.eyes': '眼睛',
    'pfp.outfit': '服装',
    'pfp.item': '道具',
    'pfp.ref_img': '参考图 (可选)',
    'pfp.bg_style': '背景风格',

    // Meme
    'tools.meme.title': '表情包工坊',
    'tools.meme.desc': '一键生成全套表情包',
    'meme.style': '风格',
    'meme.define': '定义标签',
    'meme.limit': '最多9个标签',
    'meme.add_input': '输入标签...',
    'meme.hint': '回车添加',
    'meme.result_title': '生成结果',
    'meme.zip': '打包下载',

    // Selfie
    'tools.selfie.title': '合影生成器',
    'tools.selfie.desc': '和你的朋友们一起合影',
    'selfie.upload_label': '上传角色图',
    'selfie.add_slot': '添加位置',
    'selfie.style': '风格',
    'selfie.scene': '场景',
    'selfie.btn': '生成合影',

    // Fortune
    'tools.fortune.title': 'AI 算命',
    'tools.fortune.desc': '测测今天的运势',
    'divine.name': '姓名',
    'divine.date': '出生日期',
    'divine.solar': '阳历',
    'divine.lunar': '阴历',
    'divine.time': '出生时辰',
    'divine.location': '出生地点',
    'divine.btn': '开始测算',
    'divine.today_done': '今日已测',
    'divine.history': '历史记录',
    'divine.result.level': '运势等级',
    'divine.result.color': '幸运色',
    'divine.result.num': '幸运数',
    'divine.result.dir': '吉位',
    'divine.result.analysis': '详细解析',

    // AI General
    'ai.click_upload': '点击上传',
    'ai.upload_base': '上传底图',
    'ai.clear': '清除',
    'ai.generating': '生成中...',
    'ai.finished': '完成',
    'ai.waiting': '等待中',
    'ai.honey_left': '剩余蜂蜜',
    'ai.start': '开始生成',
    'ai.download': '下载',
    'ai.reset': '重置',
    'ai.login_hint': '请先登录使用',

    // Games
    'games.lobby': '游戏大厅',
    'games.logged_in': '已登录',
    'games.login_save': '登录存档',
    'games.select': '选择游戏',
    'games.earn_honey': '赚取蜂蜜',
    'games.play_now': '开始游戏',
    'games.how_to_play': '玩法说明',
    'games.leaderboard': '排行榜',
    'games.reviews': '评价',
    'games.my_best': '我的最佳',
    'games.all_games': '所有游戏',
    'games.select_hint': '点击选择游戏',

    // Game Titles
    'game.bee_chess.name': '蜜蜂象棋',
    'game.bee_chess.desc': '联机象棋对战，策略博弈。',
    'game.honey_jump.name': '蜂蜜跳一跳',
    'game.honey_jump.desc': '蓄力跳跃，探索更高处。',
    'game.honey_farm.name': '蜜蜂农场',
    'game.honey_farm.desc': '种植作物，躺着赚蜂蜜。',
    'game.honey_fishing.name': '垂钓大师',
    'game.honey_fishing.desc': '钓鱼佬永不空军！',
    'game.bee_knight.name': '蜜蜂骑士',
    'game.bee_knight.desc': '极速送餐，躲避障碍。',
    'game.flappy_bee.name': '笨鸟先飞',
    'game.flappy_bee.desc': '经典玩法，挑战极限。',
    'game.honey_miner.name': '黄金矿工',
    'game.honey_miner.desc': '抓取比特币和以太坊！',
    'game.bee_defense.name': '保卫狗头',
    'game.bee_defense.desc': '拍死蜜蜂，保护狗狗。',
    'game.bee_racing.name': '极速赛车',
    'game.bee_racing.desc': '左右变道，极速狂飙。',
    'game.bee_snake.name': '贪吃蛇',
    'game.bee_snake.desc': '吃掉蜂蜜变长。',
    'game.bee_volley.name': '沙滩排球',
    'game.bee_volley.desc': '别让球落地！',
    'game.bee_run.name': '重力跑酷',
    'game.bee_run.desc': '反转重力，穿越隧道。',
    'game.honey_stack.name': '堆蛋糕',
    'game.honey_stack.desc': '完美重叠，堆得更高。',
    'game.fud_buster.name': '切水果',
    'game.fud_buster.desc': '切碎 FUD，保护绿线。',
    'game.bee_evolution.name': '合成大蜜蜂',
    'game.bee_evolution.desc': '2048 玩法，合成进化。',
    'game.bee_tile_match.name': '羊了个羊',
    'game.bee_tile_match.desc': '消除三个相同图案。',
    'game.honey_climber.name': '爬树高手',
    'game.honey_climber.desc': '左右闪避，快速攀爬。',
    'game.honey_swing.name': '蜘蛛侠',
    'game.honey_swing.desc': '像蜘蛛侠一样飞荡。',
    'game.honey_slots.name': '老虎机',
    'game.honey_slots.desc': 'Spin to win big.',
    'game.honey_burger.name': '做汉堡',
    'game.honey_burger.desc': '记忆配方，制作汉堡。',
    'game.honey_scratch.name': '刮刮乐',
    'game.honey_scratch.desc': '刮开图层，集齐三个图案中奖。',
    'game.moon_doom.name': '传奇交易员',
    'game.moon_doom.desc': '真实行情模拟，做多做空赚收益。',
    'game.bee_swarm.name': '蜜蜂突围',
    'game.bee_swarm.desc': '聚集蜂群，冲破障碍。',

    // Shop
    'shop.title': '蜂蜜商店',
    'shop.subtitle': '兑换周边与虚拟物品',
    'shop.tab.store': '商品列表',
    'shop.tab.orders': '我的订单',
    'shop.empty': '暂无商品',
    'shop.sold_out': '已售罄',
    'shop.limit_reached': '限购',
    'shop.stock': '库存',
    'shop.limit': '限购 {n}',
    'shop.redeem': '兑换',
    'shop.empty_orders': '暂无订单',
    'shop.order.paid': '实付',
    'shop.order.status.completed': '已完成',
    'shop.order.status.rejected': '已拒绝',
    'shop.order.status.pending': '处理中',
    'shop.confirm.title': '确认兑换',
    'shop.confirm.desc': '请填写收货信息',
    'shop.confirm.processing': '处理中...',
    'shop.confirm.btn': '确认支付',

    // Mission
    'mission.title': '任务中心',
    'mission.tab.earn': '赚蜂蜜',
    'mission.tab.leaderboard': '排行榜',
    'mission.tab.guide': '指南',
    'mission.desc': '完成任务获取蜂蜜，用于游戏和兑换。',
    'mission.checkin.title': '每日签到',
    'mission.checkin.desc': '每天来领低保',
    'mission.checkin.done': '已签到',
    'mission.checkin.btn': '签到',
    'mission.game.title': '每日首玩',
    'mission.game.desc': '玩任意游戏一局',
    'mission.game.btn': '去玩游戏',
    'mission.leaderboard.title': '财富榜',
    'mission.leaderboard.desc': '谁是蜂蜜大户？',
    'mission.my_rank': '我的排名',
    'mission.my_assets': '我的资产',
    'mission.guide.what': '什么是蜂蜜？',
    'mission.guide.what_desc': '蜂蜜是 BeeDog 社区的积分，通过游戏和任务获得。',
    'mission.guide.use': '用途',
    'mission.guide.use_game': '玩游戏 (如抓娃娃)',
    'mission.guide.use_ai': '使用 AI 工具',
    'mission.guide.use_future': '兑换周边',
    'mission.guide.disclaimer': '免责声明',
    'mission.guide.disclaimer_desc': '蜂蜜仅为娱乐积分，无货币价值。',

    // Board
    'board.title': '社区留言板',
    'board.desc': '留下你的足迹，全网可见',
    'board.placeholder': '说点什么...',
    'board.login_to_post': '登录后留言',
    'board.empty': '暂无留言',
    'board.be_first': '成为第一个留言的人！',
    'board.warn': '请文明发言',
  },
  en: {
    // Nav
    'brand.name': 'BeeDog',
    'nav.origin': 'Lore',
    'nav.board': 'Board',
    'nav.games': 'Games',
    'nav.tools': 'AI Tools',
    'nav.shop': 'Shop',
    'nav.admin': 'Admin',
    'nav.switch': '中',
    'nav.login': 'Login',
    'nav.missions': 'Missions',
    'nav.profile': 'Profile',

    // Hero
    'hero.tag': 'Viral Dog Sticker',
    'hero.title.1': 'Face Swollen',
    'hero.title.2': 'But Stronger',
    'hero.desc': 'From TikTok charts to the crypto space. We are $BeeDog. Life might sting sometimes, but we smile through it because the swelling is just packed with dreams and riches.',
    'hero.buy': 'Buy $BEEDOG',
    'hero.telegram': 'Join Telegram',

    // Narrative
    'narrative.title': 'The Narrative: Resilience in Puffy Faces',
    'narrative.subtitle': 'More than a meme, it\'s our spiritual totem',
    'narrative.card1.title': 'For Everyone Ever "Stung" by the Market',
    'narrative.card1.desc': 'The origin of BeeDog is a viral photo: a Minpin puppy with a hilariously swollen face after trying to taste honey. This visual conflict of "helpless yet funny" perfectly mirrors the retail investor\'s experience. We\'ve all been "stung" by whales or market volatility. Our faces are swollen, but our eyes still crave the honey (profits). It\'s a symbol of self-deprecation and persistence.',
    'narrative.card2.title': 'Social Currency of the Cyber World',
    'narrative.card2.desc': 'On platforms like WeChat and TikTok, #BeeDog has billions of views. It\'s no longer just a pet; it\'s a social language for "life is hard, but I\'m cute." When you don\'t want to work or just got liquidated, a BeeDog sticker says it all. It\'s a universal language because it touches the human core: finding humor in adversity.',

    // Community
    'comm.title': 'Community Development',
    'comm.subtitle': 'An epic journey from abandonment to self-redemption.',
    'comm.cto.title': 'The Legend of 100% Community Takeover',
    'comm.cto.desc': 'BeeDog was initially launched by an anonymous dev who abandoned it early on. The community refused to let it die. In a historic "rescue mission," we took over without VCs or insider bags. We reorganized through decentralized collaboration. Like bees building a hive, every block was laid by a real holder.',
    'comm.meme.title': 'Co-creation Lab',
    'comm.meme.desc': 'Our members are genius creators. From Naruto BeeDog to Cyber BeeDog, hundreds of new memes are born daily. This is a living IP.',
    'comm.meme.quote': '“Devs might rug, but memes are forever. As long as people post BeeDog, the consensus grows.”',
    'comm.meme.btn': 'Make Memes',
    'comm.shield.title': 'Diamond Hand Trials',
    'comm.shield.desc': 'Through deep-V recoveries, the community filtered out the true believers. Swelling heals; the moon is forever.',
    'comm.global.title': 'Global Expansion',
    'comm.global.desc': 'Exploding from the Chinese community to SEA, Europe, and NA. $BeeDog is the stickiest community coin.',

    // Token
    'token.title': 'Tokenomics',
    'token.desc': 'Transparent, community-owned. No complex lockups, no hidden pressure.',
    'token.supply': 'Total Supply',
    'token.contract': 'Contract',

    // Roadmap
    'roadmap.title': 'The Plan (Roadmap)',
    'roadmap.p1.phase': 'Phase 1',
    'roadmap.p1.title': 'Spreading Honey',
    'roadmap.p1.i1': '1.0 Infrastructure Setup',
    'roadmap.p1.i2': 'Global Meme Sync',
    'roadmap.p1.i3': '50+ Top KOL Collaborations',
    'roadmap.p1.i4': 'Initial AI PFP Tools',
    'roadmap.p2.phase': 'Phase 2',
    'roadmap.p2.title': 'Total Swelling',
    'roadmap.p2.i1': 'BeeDog Merch (Blind Boxes)',
    'roadmap.p2.i2': 'Global Meme Video Contest',
    'roadmap.p2.i3': '50,000+ Holders',
    'roadmap.p2.i4': 'More Play-to-Earn Web3 Games',
    'roadmap.p3.phase': 'Phase 3',
    'roadmap.p3.title': 'To The Moon',
    'roadmap.p3.i1': 'Top-tier CEX Listings',
    'roadmap.p3.i2': 'BeeDog Charity Foundation',
    'roadmap.p3.i3': 'BeeDog Metaverse Social Space',
    'roadmap.p3.i4': 'Top 10 Global Meme Brand',

    // Footer
    'footer.desc': 'BeeDog Community: We don\'t fear the stings.',
    'footer.risk': 'Investments are risky. Ensure you have a "swollen heart" for the ride.',
    'footer.copy': '© 2024 BeeDog Community. Driven by Diamond Hands.',

    // Auth
    'auth.welcome': 'Welcome Back',
    'auth.join': 'Join Us',
    'auth.login_desc': 'Login to save progress',
    'auth.register_desc': 'Create Account',
    'auth.twitter': 'Login with Twitter',
    'auth.or': 'OR',
    'auth.email_placeholder': 'Email Address',
    'auth.pwd_placeholder': 'Password',
    'auth.forgot_pwd': 'Forgot Password?',
    'auth.login_btn': 'Login',
    'auth.no_account': 'No account?',
    'auth.go_register': 'Register',
    'auth.has_account': 'Have account?',
    'auth.go_login': 'Login',
    'auth.register_btn': 'Register',
    'auth.forgot_title': 'Reset Password',
    'auth.forgot_desc': 'Enter email to reset',
    'auth.send_reset': 'Send Link',
    'auth.back_login': 'Back to Login',

    // Profile
    'profile.title': 'Profile',
    'profile.manage': 'Manage Account',
    'profile.no_email': 'No Email',
    'profile.honey_balance': 'Honey Balance',
    'profile.linked_acc': 'Linked Accounts',
    'profile.bind_x_done': 'Twitter Linked',
    'profile.bind_x': 'Link Twitter',
    'profile.bind_email_done': 'Email Linked',
    'profile.bind_email': 'Link Email',
    'profile.logout': 'Logout',

    // Tools
    'tools.back': 'Back',
    'tools.title': 'AI Toolbox',
    'tools.subtitle': 'Empowering Creation',
    'tools.use_now': 'Use Now',
    'tools.hot': 'HOT',
    'tools.new': 'NEW',
    'tools.daily': 'DAILY',

    // PFP
    'tools.pfp.title': 'PFP Maker',
    'tools.pfp.desc': 'Create your unique PFP',
    'pfp.mode.role': 'Roleplay',
    'pfp.mode.parts': 'Parts',
    'pfp.theme': 'Theme',
    'pfp.role': 'Role',
    'pfp.details': 'Details',
    'pfp.head': 'Head',
    'pfp.eyes': 'Eyes',
    'pfp.outfit': 'Outfit',
    'pfp.item': 'Item',
    'pfp.ref_img': 'Ref Image (Optional)',
    'pfp.bg_style': 'Background',

    // Meme
    'tools.meme.title': 'Meme Lab',
    'tools.meme.desc': 'Generate Sticker Pack',
    'meme.style': 'Style',
    'meme.define': 'Labels',
    'meme.limit': 'Max 9 labels',
    'meme.add_input': 'Add label...',
    'meme.hint': 'Enter to add',
    'meme.result_title': 'Results',
    'meme.zip': 'Download ZIP',

    // Selfie
    'tools.selfie.title': 'Group Selfie',
    'tools.selfie.desc': 'Take a selfie with friends',
    'selfie.upload_label': 'Upload Characters',
    'selfie.add_slot': 'Add Slot',
    'selfie.style': 'Style',
    'selfie.scene': 'Scene',
    'selfie.btn': 'Generate Selfie',

    // Fortune
    'tools.fortune.title': 'AI Fortune',
    'tools.fortune.desc': 'Daily Fortune',
    'divine.name': 'Name',
    'divine.date': 'Date of Birth',
    'divine.solar': 'Solar',
    'divine.lunar': 'Lunar',
    'divine.time': 'Time',
    'divine.location': 'Location',
    'divine.btn': 'Divinate',
    'divine.today_done': 'Done Today',
    'divine.history': 'History',
    'divine.result.level': 'Level',
    'divine.result.color': 'Lucky Color',
    'divine.result.num': 'Lucky Number',
    'divine.result.dir': 'Direction',
    'divine.result.analysis': 'Analysis',

    // AI General
    'ai.click_upload': 'Click Upload',
    'ai.upload_base': 'Base Image',
    'ai.clear': 'Clear',
    'ai.generating': 'Generating...',
    'ai.finished': 'Finished',
    'ai.waiting': 'Waiting',
    'ai.honey_left': 'Honey Left',
    'ai.start': 'Start',
    'ai.download': 'Download',
    'ai.reset': 'Reset',
    'ai.login_hint': 'Please login',

    // Games
    'games.lobby': 'Game Lobby',
    'games.logged_in': 'Logged In',
    'games.login_save': 'Login to Save',
    'games.select': 'Select Game',
    'games.earn_honey': 'Earn Honey',
    'games.play_now': 'Play Now',
    'games.how_to_play': 'How to Play',
    'games.leaderboard': 'Leaderboard',
    'games.reviews': 'Reviews',
    'games.my_best': 'My Best',
    'games.all_games': 'All Games',
    'games.select_hint': 'Click to select',

    // Game Titles
    'game.bee_chess.name': 'Bee Chess',
    'game.bee_chess.desc': 'Online multiplayer Chinese Chess.',
    'game.honey_jump.name': 'Honey Jump',
    'game.honey_jump.desc': 'Charge and jump to the sky.',
    'game.honey_farm.name': 'Honey Farm',
    'game.honey_farm.desc': 'Plant and earn honey idle.',
    'game.honey_fishing.name': 'Fishing Master',
    'game.honey_fishing.desc': 'Catch rare fish!',
    'game.bee_knight.name': 'Bee Knight',
    'game.bee_knight.desc': 'Deliver food, dodge cars.',
    'game.flappy_bee.name': 'Flappy Bee',
    'game.flappy_bee.desc': 'Classic flying challenge.',
    'game.honey_miner.name': 'Honey Miner',
    'game.honey_miner.desc': 'Grab BTC and ETH!',
    'game.bee_defense.name': 'Bee Defense',
    'game.bee_defense.desc': 'Smack bees, save dog.',
    'game.bee_racing.name': 'Bee Racing',
    'game.bee_racing.desc': 'Dodge traffic at high speed.',
    'game.bee_snake.name': 'Bee Snake',
    'game.bee_snake.desc': 'Eat honey to grow.',
    'game.bee_volley.name': 'Bee Volley',
    'game.bee_volley.desc': 'Don\'t let the ball drop!',
    'game.bee_run.name': 'Gravity Run',
    'game.bee_run.desc': 'Flip gravity, run fast.',
    'game.honey_stack.name': 'Honey Stack',
    'game.honey_stack.desc': 'Stack blocks perfectly.',
    'game.fud_buster.name': 'FUD Buster',
    'game.fud_buster.desc': 'Slice FUD, keep green.',
    'game.bee_evolution.name': 'Bee Evolution',
    'game.bee_evolution.desc': 'Merge balls to evolve.',
    'game.bee_tile_match.name': 'Bee Match',
    'game.bee_tile_match.desc': 'Match 3 tiles.',
    'game.honey_climber.name': 'Honey Climber',
    'game.honey_climber.desc': 'Climb fast, dodge branches.',
    'game.honey_swing.name': 'Honey Swing',
    'game.honey_swing.desc': 'Swing like Spiderman.',
    'game.honey_slots.name': 'Honey Slots',
    'game.honey_slots.desc': 'Spin to win big.',
    'game.honey_burger.name': 'Honey Burger',
    'game.honey_burger.desc': 'Memorize and build burgers.',
    'game.honey_scratch.name': 'Scratch Card',
    'game.honey_scratch.desc': 'Scratch for surprise.',
    'game.moon_doom.name': 'Legendary Trader',
    'game.moon_doom.desc': 'Simulate crypto trading.',
    'game.bee_swarm.name': 'Bee Swarm',
    'game.bee_swarm.desc': 'Gather swarm, break through.',

    // Shop
    'shop.title': 'Honey Shop',
    'shop.subtitle': 'Redeem Merch & Items',
    'shop.tab.store': 'Store',
    'shop.tab.orders': 'Orders',
    'shop.empty': 'No products',
    'shop.sold_out': 'Sold Out',
    'shop.limit_reached': 'Limit',
    'shop.stock': 'Stock',
    'shop.limit': 'Limit {n}',
    'shop.redeem': 'Redeem',
    'shop.empty_orders': 'No orders',
    'shop.order.paid': 'Paid',
    'shop.order.status.completed': 'Completed',
    'shop.order.status.rejected': 'Rejected',
    'shop.order.status.pending': 'Pending',
    'shop.confirm.title': 'Confirm',
    'shop.confirm.desc': 'Enter Details',
    'shop.confirm.processing': 'Processing...',
    'shop.confirm.btn': 'Pay',

    // Mission
    'mission.title': 'Mission Center',
    'mission.tab.earn': 'Earn',
    'mission.tab.leaderboard': 'Leaderboard',
    'mission.tab.guide': 'Guide',
    'mission.desc': 'Complete missions to earn Honey.',
    'mission.checkin.title': 'Daily Check-in',
    'mission.checkin.desc': 'Free honey daily',
    'mission.checkin.done': 'Checked In',
    'mission.checkin.btn': 'Check In',
    'mission.game.title': 'Daily Play',
    'mission.game.desc': 'Play any game once',
    'mission.game.btn': 'Play Game',
    'mission.leaderboard.title': 'Rich List',
    'mission.leaderboard.desc': 'Who has most honey?',
    'mission.my_rank': 'My Rank',
    'mission.my_assets': 'My Assets',
    'mission.guide.what': 'What is Honey?',
    'mission.guide.what_desc': 'Honey is community points earned by playing.',
    'mission.guide.use': 'Uses',
    'mission.guide.use_game': 'Play Games',
    'mission.guide.use_ai': 'Use AI Tools',
    'mission.guide.use_future': 'Redeem Merch',
    'mission.guide.disclaimer': 'Disclaimer',
    'mission.guide.disclaimer_desc': 'Honey is for entertainment only.',

    // Board
    'board.title': 'Community Board',
    'board.desc': 'Leave your mark',
    'board.placeholder': 'Say something...',
    'board.login_to_post': 'Login to post',
    'board.empty': 'No messages',
    'board.be_first': 'Be the first!',
    'board.warn': 'Be polite',
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: any) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('zh'); // Default to Chinese

  const t = (key: string, params?: any): string => {
    let text = translations[language][key] || translations['en'][key] || key;
    if (params) {
        Object.keys(params).forEach(k => {
            text = text.replace(`{${k}}`, params[k]);
        });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useAuth must be used within an AuthProvider');
  }
  return context;
};
